name: Prepare Database

on:
  push:
    branches:
      - deploy

jobs:
  "set-up-sample-data":
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Remove Database
        run: npm run remove-sample-data -- "mongodb://127.0.0.1:27017/my_library_db"
      
      - name: Insert Sample Data
        run: npm run insert-sample-data -- "mongodb://127.0.0.1:27017/my_library_db"
